{"cells":[{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true},"id":"dLgYAGgjKTj0","outputId":"63fe624c-ce61-4120-af2b-3ed9c2893dd0"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-4-4f1326e428de>\", line 1, in <cell line: 1>\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/프로젝트 폴더/data/data_list')\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.9/inspect.py\", line 1543, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.9/inspect.py\", line 1501, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.9/inspect.py\", line 709, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.9/inspect.py\", line 738, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.9/inspect.py\", line 722, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.9/posixpath.py\", line 380, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-4-4f1326e428de>\", line 1, in <cell line: 1>\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/프로젝트 폴더/data/data_list')\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.9/inspect.py\", line 1543, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.9/inspect.py\", line 1501, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.9/inspect.py\", line 709, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.9/inspect.py\", line 738, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.9/inspect.py\", line 722, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.9/posixpath.py\", line 380, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-4-4f1326e428de>\", line 1, in <cell line: 1>\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/프로젝트 폴더/data/data_list')\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.9/inspect.py\", line 1543, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.9/inspect.py\", line 1501, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.9/inspect.py\", line 709, in getsourcefile\n","    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n","  File \"/usr/lib/python3.9/inspect.py\", line 738, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.9/inspect.py\", line 722, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.9/posixpath.py\", line 380, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["%cd /content/drive/MyDrive/프로젝트 폴더/data/data_list"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"id":"jbOMscIJlEQN","outputId":"8c9bfecf-2b3b-410f-fa56-6a0cd7ac99f9"},"outputs":[{"name":"stdout","output_type":"stream","text":["<Response [200]>\n","1250350\n"]}],"source":["import requests\n","import pandas as pd\n","# api 키설정\n","apikey = '785a726b62746a653536736a6d5045'\n","\n","\n","# 요청 link 리스트\n","link_list = [\n","            #  ('Vwsm_TrdhlWrcPopltnQq', '상권배후지-직장인구'),  O\n","            #  ('VwsmTrdarWrcPopltnQq', '상권-직장인구'), O\n","            #  ('VwsmTrdhlStorQq', '상권배후지-점포'),  O\n","            #  ('VwsmTrdarStorQq', '상권-점포'),          \n","            #  ('VwsmTrdhlNcmCnsmpQq', '상권배후지-소득소비'),  O\n","            #  ('VwsmTrdhlFlpopQq', '상권배후지-생활인구'), O\n","            #  ('VwsmTrdarFlpopQq', '상권-생활인구'), O\n","            #  ('VwsmTrdhlRepopQq', '상권배후지-상주인구'), O\n","            #  ('VwsmTrdarRepopQq', '상권-상주인구'), O\n","            #  ('VwsmTrdhlFcltyQq', '상권배후지-집객시설'), O\n","            #  ('VwsmTrdarFcltyQq', '상권-집객시설'), O\n","             ('VwsmTrdhlSelngQq', '상권배후지-추정매출'),  \n","            #  ('VwsmTrdarSelngQq', '상권-추정매출'),        \n","            #  ('VwsmTrdarIxQq', '상권-상권변화지표'),\n","            #  ('SPOP_FORN_TEMP_RESD_DONG', '행정동_단위_서울_생활인구(단기체류_외국인)'),\n","            #  ('ppsLongResd', '행정동_단위_서울_생활인구(장기체류_외국인)')\n","            #  ('TbgisTrdarRelm', '상권영역')\n","             ]\n","\n","for link,name in link_list:\n","  # 데이터 시작,끝설정\n","  startnum = 1\n","  endnum = 1\n","  url = f'http://openapi.seoul.go.kr:8088/{apikey}/json/{link}/{startnum}/{endnum}/'\n","  # json 형태로 전달\n","  json1 = requests.get(url)\n","  # json 요청 응답 코드\n","  json1.raise_for_status()\n","  # 한글 깨짐 인코딩 변경\n","  json1.encoding = 'utf-8'\n","\n","  # json 파일 불러오기\n","  json_file = json1.json()\n","\n","  # json 데이터 총 갯수\n","  data_len = json_file[link]['list_total_count']\n","  print(data_len)\n","\n","  # 기본 데이터프레임\n","  data = pd.DataFrame(json_file[link]['row'])\n","\n","  # data 요청, dataframe 저장\n","  for i in range(data_len//1000+1):\n","    startnum = 1000*i+2\n","    endnum = 1000*i+1001\n","    url = f'http://openapi.seoul.go.kr:8088/{apikey}/json/{link}/{startnum}/{endnum}/'\n","    json1 = requests.get(url)\n","    json1.raise_for_status()\n","    json1.encoding = 'UTF-8'\n","    json_file = json1.json()\n","    # print(json_file[link]['RESULT'])\n","    append_data = pd.DataFrame(json_file[link]['row'])\n","    append_data.reset_index(drop=True)\n","    data = pd.concat([data,append_data])\n","\n","  # dataframe 정렬 후 csv파일 저장 \n","  data.sort_values(by=[data.columns[0], data.columns[1]])\n","  data.to_csv(f\"{name}.csv\", encoding='utf-8-sig',index=False)\n","  print(f\"{name}.csv, 행 {len(data)}개 저장완료\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"FEy5kPEWMTlR"},"outputs":[],"source":["# 상권-소득소비 - 데이터가 연도별, 분기별로 따로 저장되어 있음\n","\n","import requests\n","import pandas as pd\n","# api 키설정\n","apikey = '785a726b62746a653536736a6d5045'\n","\n","\n","# 요청 link 리스트\n","link_list = [('trdarNcmCnsmp', '상권-소득소비')]\n","year = [2017,2018,2019,2020,2021,2022]\n","quarter = [1,2,3,4]\n","for link,name in link_list:\n","  for y in year:\n","    for q in quarter:\n","      # 데이터 시작,끝설정\n","      startnum = 1\n","      endnum = 1\n","      url = f'http://openapi.seoul.go.kr:8088/{apikey}/json/{link}/{startnum}/{endnum}/{y}/{q}'\n","      # json 형태로 전달\n","      json1 = requests.get(url)\n","      print(json1)\n","\n","      # 한글 깨짐 인코딩 변경\n","      json1.raise_for_status()\n","      json1.encoding = 'utf-8'\n","\n","      # json 파일 불러오기\n","      json_file = json1.json()\n","\n","      # json 데이터 개수\n","      data_len = json_file[link]['list_total_count']\n","      print(data_len)\n","      # 기본 데이터프레임\n","      data = pd.DataFrame(json_file[link]['row'])\n","\n","      # data 추출, dataframe 저장\n","      for i in range(data_len//1000+1):\n","        startnum = 1000*i+2\n","        endnum = 1000*i+1001\n","        url = f'http://openapi.seoul.go.kr:8088/{apikey}/json/{link}/{startnum}/{endnum}/{y}/{q}'\n","        json1 = requests.get(url)\n","        json1.raise_for_status()\n","        json1.encoding = 'UTF-8'\n","        json_file = json1.json()\n","        # print(json_file[link]['RESULT'])\n","        append_data = pd.DataFrame(json_file[link]['row'])\n","        append_data.reset_index(drop=True)\n","        data = pd.concat([data,append_data])\n","\n","  # dataframe 정렬 후 csv파일 저장 \n","  data.sort_values(by=[data.columns[0], data.columns[1]])\n","  data.to_csv(f\"{name}.csv\", encoding='utf-8-sig',index=False)\n","  print(f\"{name}.csv, 행 {len(data)}개 저장완료\")"]}],"metadata":{"colab":{"provenance":[],"mount_file_id":"1U9A4LEOcW47fazb-VONG8qZYG0BNsZ2I","authorship_tag":"ABX9TyOdX0pXaQ+Q7WHa2i/LfbEC"},"gpuClass":"standard","kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}